#!/usr/bin/env node
/**
 * Shared build library for the native plane — the one place that knows
 * how a wasm artifact is compiled, pinned, and embedded.
 *
 * Each module's build.mjs is a thin manifest that calls in here:
 *
 *   - requirePinnedZig(): resolve the zig binary and enforce the
 *     toolchain pin in native/.zig-version (textops and the launcher
 *     build through the zig toolchain), so codegen drift between
 *     releases can't break the CI drift diff.
 *   - cargoBuildWasm(): drive cargo to wasm32-unknown-unknown with the
 *     path remapping that keeps output machine-independent. The
 *     toolchain pin lives in each crate's rust-toolchain.toml. Exports
 *     are declared in-source via #[export_name = "..."].
 *   - embedWasm(): write the base64 `*-bytes.ts` module that is the
 *     runtime artifact of record (survives `bun build --compile`
 *     single binaries — no fs paths or import.meta.url asset lookups).
 *
 * Uses only node builtins so it runs on the bare runner node in CI
 * without an `npm ci`.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const sharedDir = dirname(fileURLToPath(import.meta.url));
const nativeDir = resolve(sharedDir, "..");
const repoRoot = resolve(nativeDir, "..");

/**
 * Resolve the zig binary (ZIG env override) and fail loudly unless it
 * matches the pin in native/.zig-version.
 */
export function requirePinnedZig() {
  const pinned = readFileSync(join(nativeDir, ".zig-version"), "utf-8").trim();
  const zig = process.env.ZIG || "zig";
  const version = execFileSync(zig, ["version"], { encoding: "utf-8" }).trim();
  if (version !== pinned) {
    console.error(
      `native: zig ${version} found, but artifacts are pinned to ` +
        `${pinned} (native/.zig-version). Install the pinned toolchain ` +
        `from https://ziglang.org/download/ or point ZIG at it.`,
    );
    process.exit(1);
  }
  return zig;
}

/**
 * Compile a Rust crate to a wasm32-unknown-unknown artifact and return
 * its path.
 *
 * Determinism: pinned compiler (the crate's rust-toolchain.toml) +
 * --locked + path remapping. rustc embeds source paths (panic
 * locations) of registry crates, which live under $CARGO_HOME — a
 * machine-dependent absolute path. Remap both the registry root and
 * the workspace to fixed virtual paths so the artifact is independent
 * of who built it and where.
 */
export function cargoBuildWasm({ moduleDir, crateName }) {
  const cargoHome = process.env.CARGO_HOME || resolve(homedir(), ".cargo");
  execFileSync(
    "cargo",
    ["build", "--release", "--target", "wasm32-unknown-unknown", "--locked"],
    {
      cwd: moduleDir,
      stdio: "inherit",
      env: {
        ...process.env,
        RUSTFLAGS: `--remap-path-prefix=${cargoHome}=/cargo-home --remap-path-prefix=${moduleDir}=/build`,
      },
    },
  );
  return join(
    moduleDir,
    "target",
    "wasm32-unknown-unknown",
    "release",
    `${crateName}.wasm`,
  );
}

/**
 * Embed a built wasm artifact as a base64 TypeScript module under
 * src/native/. CI rebuilds and diffs the generated file to guarantee
 * it matches the committed source.
 */
export function embedWasm({
  wasmPath,
  outFile,
  constName,
  sourceDir,
  rebuildCmd,
  consumer,
  target = "wasm32-freestanding",
}) {
  const wasm = readFileSync(wasmPath);
  const base64 = wasm.toString("base64");
  const outPath = join(repoRoot, "src", "native", outFile);

  // Keep the emitted shape prettier-stable (printWidth 80: assignment
  // breaks after `=`, string stays on one indented line — prettier
  // never wraps string literals).
  const ts = `// Generated by native/shared/build-lib.mjs — do not edit by hand.
// Rebuild with \`${rebuildCmd}\` after changing the source.
// Source: ${sourceDir} (${wasm.length} bytes of ${target}).

/** ${sourceDir} artifact, base64-encoded. Decoded + instantiated lazily by ${consumer}. */
export const ${constName} =
  "${base64}";
`;

  writeFileSync(outPath, ts);
  console.log(
    `embedded ${wasm.length} bytes of wasm (${base64.length} base64 chars) -> ${outPath}`,
  );
}
