#!/usr/bin/env node
/**
 * Shared build library for the native plane — the one place that knows
 * how a wasm artifact is compiled, pinned, and embedded.
 *
 * Each module's build.mjs is a thin manifest that calls in here:
 *
 *   - requirePinnedZig(): resolve the zig binary and enforce the
 *     toolchain pin in native/.zig-version (one pin for every module
 *     that builds through the zig toolchain — Zig, C, and C++ alike),
 *     so codegen drift between releases can't break the CI drift diff.
 *   - compileWasm(): drive `zig cc` / `zig c++` to wasm32-freestanding
 *     with the flag set that keeps output deterministic (-g0, stripped,
 *     no host paths). Exports are declared in-source via
 *     __attribute__((export_name(...))).
 *   - embedWasm(): write the base64 `*-bytes.ts` module that is the
 *     runtime artifact of record (survives `bun build --compile`
 *     single binaries — no fs paths or import.meta.url asset lookups).
 *
 * Uses only node builtins so it runs on the bare runner node in CI
 * without an `npm ci`.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const sharedDir = dirname(fileURLToPath(import.meta.url));
const nativeDir = resolve(sharedDir, "..");
const repoRoot = resolve(nativeDir, "..");

/**
 * Resolve the zig binary (ZIG env override) and fail loudly unless it
 * matches the pin in native/.zig-version.
 */
export function requirePinnedZig() {
  const pinned = readFileSync(join(nativeDir, ".zig-version"), "utf-8").trim();
  const zig = process.env.ZIG || "zig";
  const version = execFileSync(zig, ["version"], { encoding: "utf-8" }).trim();
  if (version !== pinned) {
    console.error(
      `native: zig ${version} found, but artifacts are pinned to ` +
        `${pinned} (native/.zig-version). Install the pinned toolchain ` +
        `from https://ziglang.org/download/ or point ZIG at it.`,
    );
    process.exit(1);
  }
  return zig;
}

/**
 * Compile C or C++ sources to a wasm32-freestanding artifact.
 *
 * Determinism: pinned compiler + fixed flags + -g0 (no debug info, no
 * host paths) + --strip-all. -fno-builtin stops clang from recognising
 * hand-written byte loops and lowering them to memcpy/memset libcalls
 * that -nostdlib cannot satisfy.
 */
export function compileWasm({ moduleDir, language, sources, outName }) {
  const zig = requirePinnedZig();
  const driver = language === "c++" ? "c++" : "cc";
  const langFlags =
    language === "c++"
      ? ["-fno-exceptions", "-fno-rtti", "-fno-threadsafe-statics"]
      : [];
  execFileSync(
    zig,
    [
      driver,
      "--target=wasm32-freestanding",
      "-O2",
      "-g0",
      "-fno-builtin",
      "-nostdlib",
      ...langFlags,
      "-Wl,--no-entry",
      "-Wl,--strip-all",
      "-o",
      outName,
      ...sources,
    ],
    {
      cwd: moduleDir,
      stdio: "inherit",
      // Keep compiler caches inside the module dir (gitignored) so
      // builds never depend on or pollute machine-global state.
      env: {
        ...process.env,
        ZIG_LOCAL_CACHE_DIR: join(moduleDir, ".zig-cache"),
        ZIG_GLOBAL_CACHE_DIR: join(moduleDir, ".zig-cache", "global"),
      },
    },
  );
}

/**
 * Embed a built wasm artifact as a base64 TypeScript module under
 * src/native/. CI rebuilds and diffs the generated file to guarantee
 * it matches the committed source.
 */
export function embedWasm({
  wasmPath,
  outFile,
  constName,
  sourceDir,
  rebuildCmd,
  consumer,
  target = "wasm32-freestanding",
}) {
  const wasm = readFileSync(wasmPath);
  const base64 = wasm.toString("base64");
  const outPath = join(repoRoot, "src", "native", outFile);

  // Keep the emitted shape prettier-stable (printWidth 80: assignment
  // breaks after `=`, string stays on one indented line — prettier
  // never wraps string literals).
  const ts = `// Generated by native/shared/build-lib.mjs — do not edit by hand.
// Rebuild with \`${rebuildCmd}\` after changing the source.
// Source: ${sourceDir} (${wasm.length} bytes of ${target}).

/** ${sourceDir} artifact, base64-encoded. Decoded + instantiated lazily by ${consumer}. */
export const ${constName} =
  "${base64}";
`;

  writeFileSync(outPath, ts);
  console.log(
    `embedded ${wasm.length} bytes of wasm (${base64.length} base64 chars) -> ${outPath}`,
  );
}
