/**
 * MCP supervisor launcher.
 *
 * Every MCP stdio server Talon hands to the Claude Agent SDK is wrapped
 * through a tiny Node supervisor: `node mcp-launcher.mjs <real-cmd> [args...]`.
 *
 * The supervisor proxies stdio between the SDK and the real child, and
 * watches its own `process.stdin` for EOF. When the SDK's pipe closes —
 * for any reason, including Talon crashing or being SIGKILLed — the
 * kernel closes our stdin, we SIGTERM the child, then SIGKILL if it
 * hasn't exited within a short grace, then exit. No orphans, no /proc
 * scan, no per-plugin signature list.
 *
 * The script is emitted as a string so it survives both `tsx` dev runs
 * (where source files live on disk) and `bun build --compile` binaries
 * (where they don't). `ensureLauncher()` writes the current source to
 * `~/.talon/mcp-launcher.mjs` on first call; re-writes are skipped when
 * content matches.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirs, files as pathFiles } from "./paths.js";

const LAUNCHER_SOURCE = `#!/usr/bin/env node
// Auto-generated by Talon. Regenerated on startup if content drifts.
//
// Supervises an MCP stdio child. Dies with the child when our own stdin
// pipe closes — which happens whenever the parent (the Claude Agent SDK,
// spawned by Talon) goes away, for any reason, on any OS Node supports.
import { spawn } from "node:child_process";

const [, , cmd, ...args] = process.argv;
if (!cmd) {
  process.stderr.write("mcp-launcher: missing command\\n");
  process.exit(2);
}

const child = spawn(cmd, args, {
  stdio: ["pipe", "pipe", "pipe"],
  env: process.env,
});

// Any pipe end-point can throw EPIPE if the other side closes mid-write.
// We silence those — the "exit" / "end" paths already drive shutdown.
const swallow = () => {};
child.stdin.on("error", swallow);
child.stdout.on("error", swallow);
child.stderr.on("error", swallow);
process.stdin.on("error", swallow);
process.stdout.on("error", swallow);
process.stderr.on("error", swallow);

process.stdin.pipe(child.stdin);
child.stdout.pipe(process.stdout);
child.stderr.pipe(process.stderr);

let terminating = false;
function terminate(exitCode) {
  if (terminating) return;
  terminating = true;
  try { child.kill("SIGTERM"); } catch {}
  const force = setTimeout(() => { try { child.kill("SIGKILL"); } catch {} }, 1000);
  force.unref?.();
  child.once("exit", () => { clearTimeout(force); process.exit(exitCode); });
}

// Parent pipe closed — cross-platform orphan guard. Works for clean exit,
// uncaught exception, SIGKILL, or the machine yanking the parent away.
process.stdin.on("end", () => terminate(0));

child.once("exit", (code, signal) => {
  if (terminating) return;
  process.exit(code ?? (signal ? 1 : 0));
});
child.once("error", (err) => {
  process.stderr.write("mcp-launcher: spawn error: " + err.message + "\\n");
  process.exit(1);
});

for (const sig of ["SIGTERM", "SIGINT", "SIGHUP"]) {
  process.on(sig, () => terminate(0));
}
`;

let ensured = false;

/**
 * Write the launcher to `~/.talon/mcp-launcher.mjs` if missing or stale.
 * Idempotent across calls; returns the absolute path.
 */
export function ensureLauncher(): string {
  if (ensured) return pathFiles.mcpLauncher;

  if (!existsSync(dirs.root)) mkdirSync(dirs.root, { recursive: true });

  let needsWrite = true;
  if (existsSync(pathFiles.mcpLauncher)) {
    try {
      needsWrite = readFileSync(pathFiles.mcpLauncher, "utf-8") !== LAUNCHER_SOURCE;
    } catch {
      /* unreadable — just rewrite */
    }
  }
  if (needsWrite) {
    writeFileSync(pathFiles.mcpLauncher, LAUNCHER_SOURCE, { mode: 0o644 });
  }

  ensured = true;
  return pathFiles.mcpLauncher;
}

/** Reset the ensured-cache. Test-only. */
export function _resetLauncherCacheForTests(): void {
  ensured = false;
}

type StdioServer = {
  command: string;
  args: string[];
  env?: Record<string, string>;
};

/**
 * Rewrite `{command, args}` so the real command runs under the launcher.
 *
 * Plugin-agnostic: the launcher doesn't know or care what it's supervising.
 * Platform-agnostic: relies on pipe EOF, which POSIX and Windows both
 * deliver when the parent end of a pipe is closed.
 */
export function wrapMcpServer<T extends StdioServer>(server: T): T {
  const launcher = ensureLauncher();
  return {
    ...server,
    command: "node",
    args: [launcher, server.command, ...server.args],
  };
}
