#!/usr/bin/env node
/**
 * Embed the built blake3-wasm artifact as a base64 TypeScript module.
 *
 * Reads target/wasm32-unknown-unknown/release/blake3_wasm.wasm and writes
 * src/native/blake3-wasm-bytes.ts. The generated TS module — not a .wasm
 * file on disk — is the runtime artifact of record: it survives
 * `bun build --compile` (single-binary installs have no source tree to
 * resolve asset paths against) and needs no fs/import.meta.url lookups.
 *
 * Run via `npm run build:wasm` (cargo build + this script). CI rebuilds
 * and diffs the generated file to guarantee it matches the Rust source.
 *
 * Uses only node builtins so it runs on the bare runner node in CI
 * without an `npm ci`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const crateDir = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(
  crateDir,
  "target",
  "wasm32-unknown-unknown",
  "release",
  "blake3_wasm.wasm",
);
const outPath = join(crateDir, "..", "..", "src", "native", "blake3-wasm-bytes.ts");

const wasm = readFileSync(wasmPath);
const base64 = wasm.toString("base64");

// Keep the emitted shape prettier-stable (printWidth 80: assignment breaks
// after `=`, string stays on one indented line — prettier never wraps
// string literals).
const ts = `// Generated by native/blake3-wasm/embed.mjs — do not edit by hand.
// Rebuild with \`npm run build:wasm\` after changing the Rust source.
// Source: native/blake3-wasm (${wasm.length} bytes of wasm32-unknown-unknown).

/** blake3-wasm artifact, base64-encoded. Decoded + instantiated lazily by src/native/blake3.ts. */
export const BLAKE3_WASM_BASE64 =
  "${base64}";
`;

writeFileSync(outPath, ts);
console.log(
  `embedded ${wasm.length} bytes of wasm (${base64.length} base64 chars) -> ${outPath}`,
);
