/**
 * Backend-agnostic stream state accumulator.
 *
 * Every backend consumes a token-by-token stream and accumulates the same
 * pieces of information: text-so-far, tool calls, trailing prose,
 * delivered-text norms, token counts, an end-of-turn flag. This module
 * owns the shape of that accumulator and the helpers that mutate it.
 *
 * Backend adapters are responsible for translating their SDK's native
 * event types into calls against this state — `appendText`,
 * `recordToolUse`, `recordToolCompletion`, `markTurnTerminated`. The
 * shared handler runtime reads from it after the loop ends.
 *
 * Why a hand-managed object instead of an EventEmitter or RxJS pipeline:
 *   - The state is mutated from exactly one place (the backend's stream
 *     loop) and read from exactly one place (the post-loop accounting).
 *     A bag-of-fields object is simpler and easier to test than a stream.
 *   - Backends with different event models (Claude SDK async iterator,
 *     Kilo SSE subscription) can both call the same mutators.
 */

import { captureDeliveredText } from "./delivered-text.js";
import { isTurnTerminator } from "../../core/tools/index.js";

// ── State shape ─────────────────────────────────────────────────────────────

/** Mutable state accumulated while iterating a backend's stream. */
export interface StreamState {
  // ── Text accumulation ─────────────────────────────────────────────────────
  /** Text in the current pre-tool segment (not yet emitted as progress). */
  currentBlockText: string;
  /** All text accumulated this turn (concatenation of every segment). */
  allResponseText: string;
  /** Text *after* the last tool call (or the entire response if no tools). */
  lastTrailingText: string;

  // ── Session ───────────────────────────────────────────────────────────────
  /** Provider-assigned session id, if one was announced during the stream. */
  newSessionId: string | undefined;

  // ── Tool tracking ─────────────────────────────────────────────────────────
  /** Total number of tool_use blocks observed this turn. */
  toolCalls: number;
  /** Set when a turn-terminator (`end_turn` / `send` / `react`) fired. */
  turnTerminated: boolean;
  /** Normalized text args captured from delivery tools — used for dedup. */
  deliveredTextNorms: string[];

  // ── Token accounting ──────────────────────────────────────────────────────
  /** Effective input tokens charged this turn. */
  sdkInputTokens: number;
  /** Output tokens generated by the model this turn. */
  sdkOutputTokens: number;
  /** Cache-read tokens (input pulled from the prompt-cache). */
  sdkCacheRead: number;
  /** Cache-creation/write tokens (new prompt-cache entries this turn). */
  sdkCacheWrite: number;

  // ── Context window ────────────────────────────────────────────────────────
  /** Current context-fill estimate (last API iteration's total input). */
  contextTokens: number;
  /** Active model's full context window in tokens, if reported by the SDK. */
  contextWindow: number | undefined;
  /** API round-trips observed this turn (deltas for multi-tool flows). */
  numApiCalls: number;

  // ── Streaming bookkeeping ─────────────────────────────────────────────────
  /** Timestamp (ms) of the last delta callback — used to throttle UI updates. */
  lastStreamUpdate: number;
}

// ── Factories ───────────────────────────────────────────────────────────────

export function createStreamState(): StreamState {
  return {
    currentBlockText: "",
    allResponseText: "",
    lastTrailingText: "",
    newSessionId: undefined,
    toolCalls: 0,
    turnTerminated: false,
    deliveredTextNorms: [],
    sdkInputTokens: 0,
    sdkOutputTokens: 0,
    sdkCacheRead: 0,
    sdkCacheWrite: 0,
    contextTokens: 0,
    contextWindow: undefined,
    numApiCalls: 0,
    lastStreamUpdate: 0,
  };
}

// ── Mutators ────────────────────────────────────────────────────────────────

/**
 * Append a text fragment to the current pre-tool segment and the
 * cumulative response. Used by streaming-delta handlers.
 */
export function appendText(state: StreamState, fragment: string): void {
  if (!fragment) return;
  state.currentBlockText += fragment;
  state.lastTrailingText += fragment;
}

/**
 * Close out the current pre-tool segment.
 *
 * Called when a tool call boundary is reached. Returns the segment text
 * (trimmed) so the caller can fire a progress-text callback, and resets
 * `currentBlockText` + `lastTrailingText` for the next segment.
 *
 * The cumulative `allResponseText` is updated with the pre-trim segment
 * so the post-turn full-text capture stays faithful to what the model
 * actually produced.
 */
export function closeCurrentSegment(state: StreamState): string {
  const raw = state.currentBlockText;
  const trimmed = raw.trim();
  if (raw) {
    state.allResponseText += raw;
    state.currentBlockText = "";
    state.lastTrailingText = "";
  }
  return trimmed;
}

/**
 * Record a tool call observed in the stream.
 *
 * Updates `toolCalls`, captures any delivered-text norm, and flips
 * `turnTerminated` when the tool is a turn terminator (with the soft-
 * terminator opt-out — `react` with `end_turn: false` keeps the turn
 * alive).
 */
export function recordToolUse(
  state: StreamState,
  toolName: string,
  toolInput: Record<string, unknown>,
): void {
  state.toolCalls += 1;
  const norm = captureDeliveredText(toolName, toolInput);
  if (norm) state.deliveredTextNorms.push(norm);
  if (isTurnTerminator(toolName, toolInput)) {
    state.turnTerminated = true;
  }
}

/**
 * Bulk-update token accounting for the turn.
 *
 * Backends call this at the end of the stream loop when their final
 * result message carries usage totals. Inputs that are `undefined` or
 * negative are coerced to 0 — defensive against partial SDK payloads.
 */
export function recordTokens(
  state: StreamState,
  tokens: {
    inputTokens?: number;
    outputTokens?: number;
    cacheRead?: number;
    cacheWrite?: number;
  },
): void {
  state.sdkInputTokens = Math.max(0, tokens.inputTokens ?? 0);
  state.sdkOutputTokens = Math.max(0, tokens.outputTokens ?? 0);
  state.sdkCacheRead = Math.max(0, tokens.cacheRead ?? 0);
  state.sdkCacheWrite = Math.max(0, tokens.cacheWrite ?? 0);
}

/**
 * Finalise the response text for the post-loop accounting.
 *
 * Concatenates the still-open `currentBlockText` onto `allResponseText`
 * (a tool-free turn never closed a segment via `closeCurrentSegment`
 * but its text still needs to land in the cumulative buffer).
 *
 * Returns the cumulative text (trimmed) so the caller can build the
 * `QueryResult.text` field.
 */
export function finalizeResponseText(state: StreamState): string {
  if (state.currentBlockText) {
    state.allResponseText += state.currentBlockText;
    state.currentBlockText = "";
  }
  return state.allResponseText.trim();
}
