#!/usr/bin/env node
/**
 * Embed the built textops-wasm artifact as a base64 TypeScript module.
 *
 * Reads textops.wasm and writes src/native/textops-wasm-bytes.ts. The
 * generated TS module — not a .wasm file on disk — is the runtime
 * artifact of record: it survives `bun build --compile` (single-binary
 * installs have no source tree to resolve asset paths against) and
 * needs no fs/import.meta.url lookups.
 *
 * Run via `npm run build:zig` (zig build + this script). CI rebuilds
 * and diffs the generated file to guarantee it matches the Zig source.
 *
 * Uses only node builtins so it runs on the bare runner node in CI
 * without an `npm ci`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const crateDir = dirname(fileURLToPath(import.meta.url));
const wasmPath = join(crateDir, "textops.wasm");
const outPath = join(crateDir, "..", "..", "src", "native", "textops-wasm-bytes.ts");

const wasm = readFileSync(wasmPath);
const base64 = wasm.toString("base64");

// Keep the emitted shape prettier-stable (printWidth 80: assignment breaks
// after `=`, string stays on one indented line — prettier never wraps
// string literals).
const ts = `// Generated by native/textops-wasm/embed.mjs — do not edit by hand.
// Rebuild with \`npm run build:zig\` after changing the Zig source.
// Source: native/textops-wasm (${wasm.length} bytes of wasm32-freestanding).

/** textops-wasm artifact, base64-encoded. Decoded + instantiated lazily by src/native/textops.ts. */
export const TEXTOPS_WASM_BASE64 =
  "${base64}";
`;

writeFileSync(outPath, ts);
console.log(
  `embedded ${wasm.length} bytes of wasm (${base64.length} base64 chars) -> ${outPath}`,
);
